### ISSUE TITLE
 "Flicker" effect on app start-up when using loading screens

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-TabletOS#12]
## Background

There is a white flicker that happens somewhere between when the system level splash screen shows, our framework loading screen shows or when the main app content first draws.

We need to figure out a way to remove this "Flicker" from the app

**Comment by tneil** [comment]
**Update...**

The long flicker has now been resolved.  The event that was waiting for the page to load before closing the loading screen was placed on the wrong event.  This caused the Web View to be shown before the content was loaded.  The initial color of the Web View is white, thus the long flicker

There is also a smaller flicker that I don't think we will be able to resolve.  This is a known AIR issue across multiple platforms.  Whenever a Web View is added to the stage of a screen there is a white flicker.  This is because the Web View is different than any of the other Flash controls. The Web View draws directly to the screen and when it initializes it flickers.

We will continue to investigate and see if there is a fix and also talk with the AIR team at RIM to see if this can be resolved in the platform in an upcoming OS release.

**Comment by nukulb** [comment]
This issue should now be closed.
