### ISSUE TITLE
Battery Information

### ISSUE THREAD

**Issue by muratGG** [blackberry/WebWorks-TabletOS#2]
Hello,

There are 2 javascript events for battery information. One of them is for state and the other is for level changes.

They both work fine.

But I need to get these information without waiting them to change, so I would display the battery information immediately.

Currently I need to wait until a change occurs which is not much usable.

Could you expose these informations to Javascript.

Thanks.

**Comment by jeffheifetz** [comment]
I believe this has been fixed in the newest SDKs that they will always fire an initial event with the current state

**Comment by muratGG** [comment]
Thanks for information, I will check this as soon as possible.
