### ISSUE TITLE
blackberry.identity.PIN always returns null

### ISSUE THREAD

**Issue by mjrusso** [blackberry/WebWorks-TabletOS#38]
We have tested this on numerous PlayBook devices and have found that the `blackberry.identity.PIN` property returns `null` under all circumstances.

The configuration document has the requisite lines set, as indicated in the [documentation](http://www.blackberry.com/developers/docs/webworks/api/blackberry.identity.html):

```
<feature id="blackberry.identity" />
<feature id="blackberry.identity.phone" />
```

_(We have also tried with `blackberry.identify.phone` removed, given that there is no phone on the PlayBook, but the results are the same.)_

We are also seeing the same result when making request to `webworks://blackberry/identity/get`.

Is there possibly some other configuration issue that would be preventing this from working?

**Comment by cdelcol** [comment]
Have you added the permissions tag in the config.xml?
Permission Elements (PlayBook Only)
You must declare the permission element(s) below in your configuration document:
- rim:permitread_device_identifying_information/rim:permit Permits your app to access device identifiers.

I believe it is of the form:

<rim:permissions>
    <rim:permit>read_device_identifying_information</rim:permit> 
</rim:permissions>

**Comment by mjrusso** [comment]
That did it, thanks. 

There is a bug in the documentation: If you filter the documentation by PlayBook only, there is no mention of `read_device_identifying_information`. However, if you filter by "Show All APIs", the following text appears:

```
Permission Elements (PlayBook Only)
You must declare the permission element(s) below in your configuration document:
- <rim:permit>read_device_identifying_information</rim:permit>
Permits your app to access device identifiers.  
```

**Comment by cdelcol** [comment]
We noticed that the other day. We are in the process of a docs cleanup and all templates are being re-vamped. The filtering function will likely disappear for awhile during the transition to a better place.

Cheers,
 
Chris.
 
Chris DelCol
Manager, BlackBerry WebWorks
Research In Motion Limited
Phone: (905) 629-4746 x15359
Email: cdelcol@rim.com

-----Original Message-----
