### ISSUE TITLE
Set a wallpaper from within an app

### ISSUE THREAD

**Issue by bglowDragosh** [blackberry/WebWorks-TabletOS#58]
Hi, 

I want to build a webworks app that has the ability of setting a home screen wallpaper on a playbook, from within that app.
Any chance access to such functionality would be granted in the near future? 

Thank you.

**Comment by williamrjribeiro** [comment]
I second that. Really looking forward for this functionality.

**Comment by bglowDragosh** [comment]
Forgot to close this issue - this can now be done using BB10 WebWorks: https://github.com/blackberry/BB10-WebWorks-Samples/tree/master/SetWallpaper
